/*
 * Hades Cluster / Shai-Hulud PyPI Supply Chain Attack - YARA Detection Rules
 * Generated by Actioner on 2026-06-07
 * References:
 *   - https://www.hendryadrian.com/shai-hulud-descends-to-hades-miasma-worm-campaign-spreads-with-new-pypi-wave/
 *   - https://snyk.io/blog/lightning-pypi-compromise-bun-based-credential-stealer/
 */

rule Malware_HadesCluster_ShaiHulud_Credential_Stealer
{
    meta:
        description = "Detects the Hades Cluster / Shai-Hulud obfuscated JavaScript credential stealer payload (_index.js / router_runtime.js)"
        author = "Actioner"
        date = "2026-06-07"
        reference = "https://www.hendryadrian.com/shai-hulud-descends-to-hades-miasma-worm-campaign-spreads-with-new-pypi-wave/"
        hash = "5f5852b5f604369945118937b058e49064612ac69826e0adadca39a357dfb5b1"
        severity = "critical"

    strings:
        $marker1 = "Hades" ascii wide
        $marker2 = "The End for the Damned" ascii wide
        $marker3 = "Mini Shai-Hulud" ascii wide
        $marker4 = "IfYouYankThisToken" ascii wide
        $marker5 = "FIRESCALE" ascii wide
        $marker6 = "OhNoWhatsGoingOnWithGitHub" ascii wide

        $cred1 = "gh-token-monitor" ascii
        $cred2 = "pgsql-monitor" ascii
        $cred3 = ".npmrc" ascii
        $cred4 = ".pypirc" ascii

        $cipher1 = "__decodeScrambled" ascii
        $cipher2 = "ctf-scramble-v2" ascii
        $cipher3 = "svksjrhjkcejg" ascii

        $regex1 = "gh[op]_[A-Za-z0-9]{36,}" ascii
        $regex2 = "npm_[A-Za-z0-9]{36,}" ascii

    condition:
        filesize < 15MB and
        (
            (2 of ($marker*)) or
            (1 of ($cipher*) and 1 of ($cred*)) or
            (1 of ($marker*) and 1 of ($regex*) and 1 of ($cred*))
        )
}

rule Supply_Chain_HadesCluster_PTH_Startup_Hook
{
    meta:
        description = "Detects malicious Python .pth startup hook files used by the Hades Cluster campaign to execute payloads during Python initialization"
        author = "Actioner"
        date = "2026-06-07"
        reference = "https://snyk.io/blog/lightning-pypi-compromise-bun-based-credential-stealer/"
        hash = "8046a11187c135da6959862ff3846e99ad15462d2ec8a2f77a30ad53ebd5dcf2"
        severity = "critical"

    strings:
        $pth_import = "import " ascii
        $bun_download = "oven-sh/bun/releases" ascii
        $bun_zip = "/tmp/b.zip" ascii
        $bun_ran = "/tmp/.bun_ran" ascii
        $start_py = "start.py" ascii
        $runtime_dir = "_runtime" ascii

    condition:
        filesize < 100KB and
        $pth_import at 0 and
        (2 of ($bun_download, $bun_zip, $bun_ran, $start_py, $runtime_dir))
}
