// ClickLock macOS Stealer - YARA Detection Rule
// Generated by Actioner on 2026-07-17
// Reference: https://www.group-ib.com/blog/clicklock-stealer-macos-malware/
// Validation: yarac exit 0

rule Malware_ClickLock_Orchestrator_Script
{
    meta:
        description = "Detects the ClickLock macOS stealer orchestrator shell script via distinctive string combinations including plist names, process kill targets, and credential validation commands"
        author = "Actioner"
        date = "2026-07-17"
        reference = "https://www.group-ib.com/blog/clicklock-stealer-macos-malware/"
        severity = "high"

    strings:
        $plist1 = "com.authirity.plist" ascii
        $plist2 = "com.chromer.plist" ascii
        $dscl = "dscl /Local/Default -authonly" ascii
        $kill1 = "killall Dock" ascii
        $kill2 = "killall Finder" ascii
        $kill3 = "NotificationCenter" ascii
        $cache = ".cacheb" ascii
        $disguise = "iCloudsync" ascii
        $goyim = "goyim" ascii

    condition:
        filesize < 500KB and
        3 of ($plist1, $plist2, $dscl, $cache, $disguise, $goyim) and
        1 of ($kill*)
}
