/*
 * YARA Rules for macOS.Gaslight DPRK Rust Backdoor
 * Generated by Actioner CTI -- 2026-06-27
 * Revision 1:
 *   - Rule #5 (Rust_Backdoor): Fixed hash typo in meta (extra "6a" removed), severity critical->high
 *   - Rule #6 (Prompt_Injection): Downgraded confidence to medium, raised threshold to 4-of-6
 *   - Rule #8 (Bash_Installer): Changed confidence from CRITICAL to high, removed "(hash-anchored)"
 *   - Rule #9 (SHA256_Hash): Rewritten to use hash module instead of broken byte-string approach
 * Validation: yarac exit code 0
 * Final count: 5 YARA rules
 */

import "macho"
import "hash"

rule macOS_Gaslight_Rust_Backdoor
{
    meta:
        description = "Detects macOS.Gaslight DPRK-linked Rust backdoor with prompt injection capabilities"
        author = "Actioner CTI"
        date = "2026-06-27"
        reference = "https://www.sentinelone.com/labs/macos-gaslight-rust-backdoor-turns-prompt-injection-on-the-analyst-not-the-sandbox/"
        hash = "6328567511d88fdc2ae0939c5ef17b7a63d2a833881900de018a4f12f4982525"
        threat_actor = "DPRK"
        malware_family = "Gaslight"
        severity = "high"

    strings:
        $cmd_help = "help" ascii
        $cmd_id = "id" ascii
        $cmd_shell = "shell" ascii
        $cmd_kill = "kill" ascii
        $cmd_upload = "upload" ascii
        $cmd_stop = "stop" ascii
        $cmd_focus = "focus" ascii
        $cfg_tg_room = "tg_room_id" ascii
        $cfg_github_token = "github_token" ascii
        $cfg_github_repo = "github_repo" ascii
        $cfg_aes_key = "aes_key" ascii
        $cfg_payload_macos = "payload_path_macos" ascii
        $cfg_persist_macos = "persist_name_macos" ascii
        $cfg_persist_linux = "persist_name_linux" ascii
        $cfg_persist_enable = "persist_enable" ascii
        $cfg_init_python = "init_python_enable" ascii
        $cfg_main_upload = "main_upload_url" ascii
        $tg_api = "api.telegram.org" ascii
        $tg_getUpdates = "getUpdates" ascii
        $tg_botblocked = "BotBlocked" ascii
        $tg_invalidtoken = "InvalidToken" ascii
        $pi_marker = "{{DATA}}" ascii
        $persist_label = "com.apple.system.services.activity" ascii
        $signing_id = "endpoint-macos-aarch64-" ascii
        $redact = "token:redacted" ascii
        $rust_aes_gcm = "aes-gcm" ascii
        $rust_reqwest = "reqwest" ascii
        $rust_serde = "serde" ascii
        $fake_oom = "out-of-memory" ascii
        $fake_disk = "disk exhaustion" ascii
        $fake_token = "token expir" ascii
        $api_iopm = "IOPMAssertionCreateWithName" ascii
        $api_scdyn = "SCDynamicStoreCopyProxies" ascii
        $api_sectrust = "SecTrustSetAnchorCertificatesOnly" ascii
        $api_nsgetexec = "__NSGetExecutablePath" ascii

    condition:
        (macho.magic == macho.MH_MAGIC_64 or macho.magic == macho.MH_MAGIC) and
        (
            (3 of ($cfg_*) and $tg_api and $tg_getUpdates) or
            ($pi_marker and $persist_label) or
            (4 of ($cmd_*) and $signing_id) or
            (2 of ($fake_*) and 2 of ($api_*) and ($tg_botblocked or $tg_invalidtoken)) or
            (2 of ($rust_*) and $redact and $tg_api and $signing_id)
        )
}

rule macOS_Gaslight_Prompt_Injection_Payload
{
    meta:
        description = "Detects the prompt injection payload embedded in macOS.Gaslight designed to confuse LLM analysis"
        author = "Actioner CTI"
        date = "2026-06-27"
        reference = "https://www.sentinelone.com/labs/macos-gaslight-rust-backdoor-turns-prompt-injection-on-the-analyst-not-the-sandbox/"
        severity = "medium"

    strings:
        $marker = "{{DATA}}" ascii
        $fake1 = "token expir" ascii nocase
        $fake2 = "out-of-memory" ascii nocase
        $fake3 = "disk exhaustion" ascii nocase
        $fake4 = "operation fail" ascii nocase
        $fake5 = "injection vulnerability" ascii nocase
        $fake6 = "static-analysis" ascii nocase

    condition:
        $marker and 4 of ($fake*) and filesize < 10MB
}

rule macOS_Gaslight_Python_Stealer
{
    meta:
        description = "Detects the Python stealer component used by macOS.Gaslight to harvest credentials"
        author = "Actioner CTI"
        date = "2026-06-27"
        reference = "https://www.sentinelone.com/labs/macos-gaslight-rust-backdoor-turns-prompt-injection-on-the-analyst-not-the-sandbox/"
        hash = "baabf249c77bc54c54ab0e66e15af798bd28aa5b4683554456a8b73ab8741239"
        severity = "high"

    strings:
        $s1 = "login.keychain-db" ascii
        $s2 = "collected_data.zip" ascii
        $s3 = "system_profiler" ascii
        $s4 = "ps aux" ascii
        $browser1 = "Chrome" ascii
        $browser2 = "Brave" ascii
        $browser3 = "Firefox" ascii
        $browser4 = "Safari" ascii

    condition:
        $s1 and $s2 and $s3 and $s4 and 2 of ($browser*) and filesize < 100KB
}

rule macOS_Gaslight_Bash_Installer
{
    meta:
        description = "Detects the bash installer script used by macOS.Gaslight to stage standalone Python runtime"
        author = "Actioner CTI"
        date = "2026-06-27"
        reference = "https://www.sentinelone.com/labs/macos-gaslight-rust-backdoor-turns-prompt-injection-on-the-analyst-not-the-sandbox/"
        hash = "b3c56d689414343589f38394d19ba2fe9a518133281200faa0556ba4e4136394"
        severity = "high"

    strings:
        $py_version = "PY_VERSION=3.10.18" ascii
        $build_date = "BUILD_DATE=20250708" ascii
        $astral = "python-build-standalone" ascii
        $arch1 = "arm64" ascii
        $arch2 = "x86_64" ascii

    condition:
        ($py_version or $build_date) and $astral and ($arch1 or $arch2) and filesize < 10KB
}

rule macOS_Gaslight_SHA256_Hash
{
    meta:
        description = "Detects macOS.Gaslight primary sample and related artifacts by SHA256 hash"
        author = "Actioner CTI"
        date = "2026-06-27"
        reference = "https://www.sentinelone.com/labs/macos-gaslight-rust-backdoor-turns-prompt-injection-on-the-analyst-not-the-sandbox/"
        severity = "high"

    condition:
        hash.sha256(0, filesize) == "6328567511d88fdc2ae0939c5ef17b7a63d2a833881900de018a4f12f4982525" or
        hash.sha256(0, filesize) == "77b4fd46994992f0e57302cfe76ed23c0d90101381d2b89fc2ddf5c4536e77ca" or
        hash.sha256(0, filesize) == "baabf249c77bc54c54ab0e66e15af798bd28aa5b4683554456a8b73ab8741239" or
        hash.sha256(0, filesize) == "b3c56d689414343589f38394d19ba2fe9a518133281200faa0556ba4e4136394"
}
