// ChocoPoC RAT - Trojanized PoC Exploit Campaign YARA Rules
// Source: https://www.sekoia.com/blog/dont-eat-the-chocopocs-how-vulnerability-researchers-were-repeatedly-targeted-by-trojanised-exploits
// Generated by Actioner, 2026-07-02

rule Malware_Python_ChocoPoC_RAT
{
    meta:
        description = "Detects ChocoPoC RAT components via distinctive strings including anti-recursion markers, Spanish-language command names, Mapbox C2 identifiers, and malicious package artifacts"
        author = "Actioner"
        date = "2026-07-02"
        reference = "https://www.sekoia.com/blog/dont-eat-the-chocopocs-how-vulnerability-researchers-were-repeatedly-targeted-by-trojanised-exploits"
        tlp = "WHITE"
        severity = "critical"
        hash_skytext = "93739477cd379adef95126b22758c0e644282d2028dd297328ce856fa111dd06"
        hash_frint = "17997e9e0256d0f5d5d21a4852c37f16b338e4bb9c2bec09bdfd822b24aa76b4"
        hash_gradient_pyd = "40569318e89db751ff3886b2617d990d8a343f0d1d8727b7f978a28129ca36bc"
        hash_gradient_so = "320b29844892e3c59bc6fcb07e701b2b3230a37cb4a13176174e9e294ec6d43e"

    strings:
        $env_anti1 = "ZEBUWIAKGPHOQAP006" ascii
        $env_anti2 = "JKHWQVEKRASDF12" ascii
        $env_val1 = "PTsjBGKQUxZorq2" ascii
        $env_val2 = "JKHKJ23VAS8DF9" ascii

        $cmd_hola = "hola" ascii
        $cmd_dormir = "dormir" ascii
        $cmd_browserdata = "browserdata" ascii

        $mapbox_dataset = "cmor0tcxf008i1mmpd7apt903" ascii
        $mapbox_feature = "dm370543acmdopk296nahbtua" ascii
        $mapbox_user1 = "frankley" ascii
        $mapbox_user2 = "mattallahsaed" ascii
        $mapbox_user3 = "james09790" ascii

        $c2_upload = "91.132.163.78" ascii
        $c2_port = ":8001" ascii
        $c2_path = "/assets/static/bundle.ext.min.de5b2bc9.js" ascii

        $xor_key = "EXPLOIT_POC.PY" ascii

        $pkg_skytext = "skytext" ascii
        $pkg_frint = "frint" ascii
        $stage2 = "choco.py" ascii

        $distutils_hook = "distutils-precedence.pth" ascii

    condition:
        filesize < 5MB and
        (
            (2 of ($env_anti1, $env_anti2, $env_val1, $env_val2)) or
            ($cmd_hola and $cmd_dormir and $cmd_browserdata) or
            (1 of ($mapbox_dataset, $mapbox_feature)) or
            ($c2_upload and $c2_path) or
            ($xor_key and 1 of ($pkg_skytext, $pkg_frint, $stage2)) or
            ($distutils_hook and 1 of ($env_anti*, $cmd_*, $mapbox_*)) or
            (6 of them)
        )
}

rule Malware_Python_ChocoPoC_Gradient_Extension
{
    meta:
        description = "Detects the ChocoPoC gradient.so/gradient.pyd native extension by embedded decryption key and anti-analysis artifacts"
        author = "Actioner"
        date = "2026-07-02"
        reference = "https://www.sekoia.com/blog/dont-eat-the-chocopocs-how-vulnerability-researchers-were-repeatedly-targeted-by-trojanised-exploits"
        tlp = "WHITE"
        severity = "critical"
        hash_gradient_pyd = "40569318e89db751ff3886b2617d990d8a343f0d1d8727b7f978a28129ca36bc"
        hash_gradient_so = "320b29844892e3c59bc6fcb07e701b2b3230a37cb4a13176174e9e294ec6d43e"

    strings:
        $xor_key = "EXPLOIT_POC.PY" ascii
        $env_marker = "ZEBUWIAKGPHOQAP006" ascii
        $hash_gate = { F4 83 5C 9C }
        $api_seed = { 1D 4E }

    condition:
        (uint32(0) == 0x464C457F or uint16(0) == 0x5A4D) and
        filesize < 10MB and
        (
            ($xor_key and $env_marker) or
            ($hash_gate and $api_seed) or
            ($xor_key and ($hash_gate or $api_seed))
        )
}
