// YARA rule for Hola Browser Supply Chain Compromise — XMRig Miner Binary
// Generated by Actioner | 2026-06-05 | Version 1.1 (FINAL)

rule SupplyChain_Hola_Browser_XMRig_Miner
{
    meta:
        description = "Detects the Hola Browser supply chain cryptominer (Troj/GoMiner-B) via XMRig-related strings found in the compromised me.exe binary"
        author = "Actioner"
        date = "2026-06-05"
        reference = "https://www.sophos.com/en-us/blog/you-do-surprise-me-exe-an-unexpected-executable-in-hola-browser"
        hash = "e3541caf708c075f0bb22fc68b03acd8457fea7cf0732ea935b1eb016d1c7721"
        severity = "high"

    strings:
        $xmrig_path = "m/cmd/xmrig-idle" ascii
        $miner_kill = "killed orphan miner pid %d" ascii
        $miner_stop = "user active, stopping miner" ascii
        $svc_name = "hola_monitor_svc" ascii
        $svc_exe = "HolaMonitorService.exe" ascii wide

    condition:
        uint16(0) == 0x5A4D and
        filesize < 10MB and
        ($xmrig_path or (2 of ($miner_kill, $miner_stop, $svc_name, $svc_exe)))
}
