/*
 * SonicWall SMA1000 Zero-Day Detection Rules (CVE-2026-83548, CVE-2026-83549)
 * Generated by Actioner - 2026-09-02
 * Effective altitude: behavioral (derived from prior UTA0533 campaign TTPs)
 */

rule SonicWall_SMA1000_Post_Exploit_Artifacts
{
    meta:
        description = "Detects post-exploitation artifacts from SonicWall SMA1000 compromises including ORANGETAIL web shell, KNUCKLEBALL dropper, Suo5 proxy, and ROOTRUN escalation tool. These malware families were deployed by UTA0533 via CVE-2026-15409/15410 and may be reused in exploitation of CVE-2026-83548/83549."
        author = "Actioner"
        date = "2026-09-02"
        reference = "https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2026-0016"
        severity = "critical"
        tlp = "WHITE"

    strings:
        $knuckleball1 = "deploy_new.py" ascii fullword
        $knuckleball2 = "agent_wp8.jar" ascii fullword
        $knuckleball3 = "agent_wp9.jar" ascii fullword

        $orangetail1 = "agent_wp9" ascii
        $orangetail2 = "Behinder" ascii nocase

        $suo5_1 = "agent_wp8" ascii
        $suo5_2 = "suo5" ascii nocase fullword

        $rootrun1 = "xzfind" ascii fullword

        $path1 = "/var/lib/unit/conf.json" ascii
        $path2 = "/var/lib/aventail" ascii
        $path3 = "__api__/login" ascii
        $path4 = "__api__/logout" ascii

        $cmd1 = "remove_hotfix" ascii
        $cmd2 = "sysCtrl.execRemoveHotfix" ascii
        $cmd3 = "rollbackConfirm" ascii

    condition:
        filesize < 10MB and
        (
            2 of ($knuckleball*) or
            all of ($orangetail*) or
            all of ($suo5_*) or
            ($rootrun1 and 1 of ($path*)) or
            (2 of ($path*) and 1 of ($cmd*)) or
            ($cmd2)
        )
}

rule SonicWall_SMA1000_SSRF_Exploit_Request
{
    meta:
        description = "Detects network capture artifacts containing SonicWall SMA1000 SSRF exploitation request patterns targeting wsproxy or internal API endpoints"
        author = "Actioner"
        date = "2026-09-02"
        reference = "https://www.rapid7.com/blog/post/etr-rapid7-mdr-team-discovers-new-sonicwall-sma1000-zero-days-being-actively-exploited-cve-2026-15409-cve-2026-15410/"
        severity = "high"
        tlp = "WHITE"

    strings:
        $wsproxy = "/wsproxy?bmID=-3389" ascii
        $ua = "SMA Connect Agent" ascii
        $api_login = "/__api__/login" ascii
        $api_logout = "/__api__/logout" ascii
        $host_local1 = "host=0.0.0.0" ascii
        $host_local2 = "host=127.0.0.1" ascii
        $host_local3 = "host=localhost" ascii

    condition:
        filesize < 50MB and
        (
            ($wsproxy and $ua) or
            ($wsproxy and 1 of ($host_local*)) or
            ($api_login and $api_logout)
        )
}
