/*
 * YARA Rules -- SharkLoader / StrikeShaker Campaign
 * Generated by Actioner CTI -- 2026-06-27
 * revision: 2026-06-27-R1 -- removed unused import "math", tightened condition branch 2, downgraded confidence
 */

rule SharkLoader_Dropper_Strings
{
    meta:
        description = "Detects SharkLoader dropper components based on distinctive string patterns and file artifacts observed in the StrikeShark campaign"
        author = "Actioner CTI"
        date = "2026-06-27"
        reference = "https://securelist.com/strikeshark-campaign/120326/"
        hash1 = "C559CC68986933200FD5D9E4388E2F58"
        hash2 = "B3352B42432DEDC4A519F011DC8B5D5A"
        confidence = "medium"

    strings:
        $loader_dll = "SystemSettings.dll" ascii wide
        $enc_module1 = "DscCoreR.mui" ascii wide
        $enc_module2 = "SyncRes.dat" ascii wide
        $enc_module2b = "SyncRest.dat" ascii wide
        $alt_mui1 = "GameInputInboxs32.mui" ascii wide
        $alt_mui2 = "VistaCompat.nls" ascii wide
        $alt_dat1 = "Ignored.Dat" ascii wide
        $alt_xml1 = "diagerr.xml" ascii wide
        $alt_etl1 = "NtfsLog.etl" ascii wide

        $path1 = "\\xwreg\\" ascii wide
        $path2 = "\\xgdf\\" ascii wide

        $dropper1 = "GoogleUpdateStepup.exe" ascii wide
        $dropper2 = "AnyConnect-win-4.10.04071-predeploy-k9exe" ascii wide

    condition:
        uint16(0) == 0x5A4D and
        (
            ($loader_dll and ($enc_module1 or $enc_module2)) or
            (any of ($path*) and 2 of ($alt_mui*, $alt_dat1, $alt_xml1, $alt_etl1, $enc_module*)) or
            (any of ($dropper*) and any of ($enc_module*))
        )
}

rule SharkLoader_APIHook_Module
{
    meta:
        description = "Detects SharkLoader SyncRes.dat API hook installer module that uses MinHook and direct syscalls for evasion"
        author = "Actioner CTI"
        date = "2026-06-27"
        reference = "https://securelist.com/strikeshark-campaign/120326/"
        hash = "9CBD560F820C95D7C38342CD558CB5C6"
        confidence = "medium"

    strings:
        $api1 = "NtOpenProcessToken" ascii
        $api2 = "NtAdjustPrivilegesToken" ascii
        $api3 = "NtWriteVirtualMemory" ascii
        $api4 = "NtAllocateVirtualMemory" ascii
        $api5 = "NtProtectVirtualMemory" ascii
        $api6 = "NtResumeThread" ascii
        $api7 = "NtGetContextThread" ascii
        $api8 = "NtCreateThreadEx" ascii
        $api9 = "NtQueueApcThread" ascii
        $api10 = "EtwEventWrite" ascii

        $hook1 = "CreateProcessA" ascii
        $hook2 = "CreateProcessW" ascii
        $hook3 = "VirtualAllocEx" ascii
        $hook4 = "VirtualProtectEx" ascii
        $hook5 = "WriteProcessMemory" ascii
        $hook6 = "ResumeThread" ascii

        $minhook = "MinHook" ascii wide
        $ldr1 = "LdrpLoaderLock" ascii
        $ldr2 = "LdrpWorkInProgress" ascii

    condition:
        uint16(0) == 0x5A4D and
        (
            (5 of ($api*) and 3 of ($hook*)) or
            ($minhook and 3 of ($api*)) or
            (any of ($ldr*) and 3 of ($api*))
        )
}
