/*
 * Chaos msaRAT Browser-Based C2 - YARA Detection Rule
 * Generated by Actioner on 2026-07-26
 * Reference: https://blog.talosintelligence.com/chaos-msarat-living-off-the-browser-to-build-covert-c2-channel/
 */

rule Malware_Chaos_msaRAT_DLL_Payload
{
    meta:
        description = "Detects the Chaos msaRAT DLL payload via distinctive CDP callback binding names and Rust/Tokio runtime strings"
        author = "Actioner"
        date = "2026-07-26"
        reference = "https://blog.talosintelligence.com/chaos-msarat-living-off-the-browser-to-build-covert-c2-channel/"
        severity = "high"

    strings:
        $bind1 = "msaOpen" ascii wide
        $bind2 = "msaClose" ascii wide
        $bind3 = "msaError" ascii wide
        $bind4 = "msaMessage" ascii wide
        $bind5 = "dataAck" ascii wide

        $cdp1 = "Runtime.addBinding" ascii
        $cdp2 = "Page.setBypassCSP" ascii
        $cdp3 = "Runtime.evaluate" ascii
        $cdp4 = "Target.createTarget" ascii

        $rust1 = "TOKIO_WORKER_THREADS" ascii
        $rust2 = "the number of hardware threads is not known for the target platform" ascii

        $export = "RUN" ascii fullword

    condition:
        uint16(0) == 0x5A4D and
        filesize < 10MB and
        (
            (3 of ($bind*)) or
            (2 of ($bind*) and 1 of ($cdp*)) or
            (2 of ($bind*) and $export and 1 of ($rust*))
        )
}
