/*
 * PaperCut NG/MF CVE-2026-81578 / CVE-2026-82078 Zero-Day Exploitation Chain
 * Generated by Actioner | 2026-09-02 | Version 1.0
 * 2 YARA rules detecting malicious Java class payloads and JDBC exploitation artifacts.
 */

rule Exploit_PaperCut_Malicious_Class_Payload
{
    meta:
        description = "Detects malicious Java .class files deployed via PaperCut CVE-2026-82078 exploitation. Matches class files containing OS command execution patterns and reconnaissance strings observed in recovered payloads."
        author = "Actioner"
        date = "2026-09-02"
        reference = "https://www.huntress.com/blog/papercut-actively-exploited"
        severity = "critical"
        tlp = "WHITE"

    strings:
        $magic = { CA FE BA BE }
        $runtime1 = "java/lang/Runtime" ascii
        $runtime2 = "getRuntime" ascii
        $exec = "exec" ascii
        $cmd1 = "whoami" ascii nocase
        $cmd2 = "cmd.exe" ascii nocase
        $cmd3 = "cmd /c" ascii nocase
        $cmd4 = "/bin/sh" ascii
        $cmd5 = "/bin/bash" ascii
        $cmd6 = "tasklist" ascii nocase
        $jdbc1 = "jdbc:derby:memory" ascii
        $jdbc2 = "jdbc:no:x" ascii
        $out_file = ".out" ascii
        $out_file2 = ".cmd" ascii

    condition:
        $magic at 0 and
        filesize < 50KB and
        ($runtime1 and $runtime2 and $exec) and
        (1 of ($cmd*) or 1 of ($jdbc*) or ($out_file and $out_file2))
}

rule Exploit_PaperCut_Derby_JDBC_Payload
{
    meta:
        description = "Detects Java class files or JAR archives containing JDBC exploitation strings used in PaperCut CVE-2026-82078 attacks to load malicious code via Derby in-memory database."
        author = "Actioner"
        date = "2026-09-02"
        reference = "https://horizon3.ai/attack-research/vulnerabilities/cve-2026-81578-cve-2026-82078/"
        severity = "high"
        tlp = "WHITE"

    strings:
        $magic_class = { CA FE BA BE }
        $magic_jar = { 50 4B 03 04 }
        $jdbc_pwn = "jdbc:derby:memory:pwn" ascii
        $jdbc_create = "create=true" ascii
        $values_cast = "VALUES CAST" ascii nocase
        $cafebabe_str = "cafebabe" ascii nocase
        $nashorn = "nashorn" ascii
        $scriptengine = "ScriptEngine" ascii

    condition:
        ($magic_class at 0 or $magic_jar at 0) and
        filesize < 5MB and
        (
            ($jdbc_pwn and $jdbc_create) or
            ($values_cast and $cafebabe_str) or
            ($nashorn and $scriptengine and 1 of ($jdbc*))
        )
}
