// YARA rule for Jscrambler 8.14.0 npm supply chain compromise — IronWorm Rust infostealer binary
// Generated by Actioner | 2026-07-13 | Version 1.0 (FINAL)
// revision: v1.0 — no changes required from critic review; KEEP verdict (medium confidence).
//   Note: torproject.org strings are legitimate Tor Project domains used by the embedded
//   Tor client; their presence is contextual, not malicious per se. Medium confidence because
//   Rust binaries may inline/obfuscate strings differently across builds; condition requires
//   convergence from three independent string clusters to minimize FP.

rule Supply_Chain_Jscrambler_IronWorm
{
    meta:
        description = "Detects IronWorm Rust infostealer binaries deployed by compromised jscrambler 8.14.0 npm package via distinctive string combination"
        author = "Actioner"
        date = "2026-07-13"
        reference = "https://thehackernews.com/2026/07/compromised-jscrambler-8140-npm-release.html"
        hash = "fbbcf4d8f98168f78f5c0c47a9ae56d59ec8ac84a7c9ca6b797fedfb8d62d2bd"
        hash2 = "b7ca95d1b23c8e67416a25cedf741de0917c2096bbc9d24649eea7853d054903"
        hash3 = "c8fd47d36bdf7c825378593ab82ed8c24d1dc52e26b507812393e24e1d5201fd"
        severity = "critical"

    strings:
        $tor1 = "check.torproject.org" ascii
        $tor2 = "archive.torproject.org" ascii
        $exfil = "temp.sh" ascii
        $npmrc = ".npmrc" ascii
        $registry = "registry.npmjs.org" ascii
        $setup_mjs = "setup.mjs" ascii
        $metamask = "MetaMask" ascii nocase
        $phantom = "Phantom" ascii nocase
        $bitwarden = "Bitwarden" ascii nocase
        $exodus = "Exodus" ascii nocase

    condition:
        filesize < 50MB and
        (
            2 of ($tor1, $tor2, $exfil) and
            1 of ($npmrc, $registry, $setup_mjs) and
            1 of ($metamask, $phantom, $bitwarden, $exodus)
        )
}
