// YARA rule for IronWorm npm supply chain attack — Rust ELF infostealer binary
// Generated by Actioner | 2026-06-05 | Version 1.1 (FINAL)
// revision: v1.1 — no changes from draft; KEEP per critic verdict (high confidence)

rule Malware_IronWorm_npm_Infostealer
{
    meta:
        description = "Detects the IronWorm Rust-compiled ELF infostealer distributed via malicious npm packages. Keys on the hardcoded BIP-39 seed phrase, C2 endpoint, and credential file paths unique to this implant."
        author = "Actioner"
        date = "2026-06-05"
        reference = "https://research.jfrog.com/post/iron-worm-shai-hulud-rustier-cousin/"
        severity = "critical"

    strings:
        // Hardcoded BIP-39 seed phrase (operator OPSEC failure)
        $seed = "bench crane defense corn wheel trial news abuse finish better paddle slush" ascii

        // Operator Ethereum address
        $eth_addr = "0x7e28D9889f414B06c19a22A9Bd316f0AC279a4d6" ascii nocase

        // C2 endpoint path
        $c2_endpoint = "/api/agent" ascii

        // Targeted credential files
        $cred1 = ".aws/credentials" ascii
        $cred2 = ".kube/config" ascii
        $cred3 = ".claude/.credentials.json" ascii
        $cred4 = ".codex/auth.json" ascii
        $cred5 = ".docker/config.json" ascii
        $cred6 = ".gemini/settings.json" ascii

        // Exodus wallet attack indicators
        $exodus1 = "webSecurity" ascii
        $exodus2 = "contextIsolation" ascii
        $exodus3 = "nodeIntegration" ascii

        // Commit spoofing strings
        $spoof1 = "claude@users.noreply.github.com" ascii
        $spoof2 = "dependabot" ascii

    condition:
        uint32(0) == 0x464C457F and
        filesize < 2MB and
        (
            $seed or
            $eth_addr or
            ($c2_endpoint and 3 of ($cred*)) or
            (4 of ($cred*) and 2 of ($exodus*)) or
            ($c2_endpoint and 1 of ($spoof*))
        )
}
