// Actioner - Fastjson @JSONType RCE (CVE-2026-16723) - YARA Rules
// Date: 2026-07-27
// Reference: https://thehackernews.com/2026/07/fastjson-1x-rce-vulnerability-targeted.html

rule Exploit_CVE_2026_16723_Fastjson_JSONType_RCE
{
    meta:
        description = "Detects Fastjson @JSONType jar:http RCE exploit payloads (CVE-2026-16723) in network captures, log files, or request bodies"
        author = "Actioner"
        date = "2026-07-27"
        reference = "https://thehackernews.com/2026/07/fastjson-1x-rce-vulnerability-targeted.html"
        tlp = "WHITE"
        severity = "critical"

    strings:
        $type_key = "\"@type\"" ascii nocase
        $jar_http = "jar:http" ascii nocase
        $jar_file_proc = "jar:file:/proc/self/fd/" ascii nocase
        $jar_file_dev = "jar:file:/dev/fd/" ascii nocase
        $probe_bang = ".probe!." ascii
        $proc_fd = "/proc/self/fd/" ascii
        $dev_fd = "/dev/fd/" ascii
        $dot_dot_pattern = "jar:http:.." ascii

    condition:
        $type_key and (
            ($jar_http and $probe_bang) or
            $dot_dot_pattern or
            ($jar_http and ($proc_fd or $dev_fd)) or
            $jar_file_proc or
            $jar_file_dev
        )
}

rule Exploit_CVE_2026_16723_Fastjson_Probe_JAR
{
    meta:
        description = "Detects the malicious probe JAR artifact generated by Fastjson CVE-2026-16723 exploit tooling containing @JSONType annotated classes"
        author = "Actioner"
        date = "2026-07-27"
        reference = "https://github.com/dinosn/fastjson-jsontype-rce-lab"
        tlp = "WHITE"
        severity = "critical"

    strings:
        $pk_header = { 50 4B 03 04 }
        $json_type_annotation = "com/alibaba/fastjson/annotation/JSONType" ascii
        $clinit = "<clinit>" ascii
        $runtime_exec = "Runtime" ascii
        $exec_method = "exec" ascii
        $probe_class = "POC.class" ascii

    condition:
        $pk_header at 0 and
        $json_type_annotation and
        $clinit and
        ($runtime_exec and $exec_method) and
        $probe_class and
        filesize < 50KB
}
