/*
 * YARA rules for Jscrambler IronWorm NPM Supply Chain Compromise (2026-07-17)
 * Source: summaries/2026-07-17-jscrambler-npm-supply-chain.md
 * Generated by Actioner
 */

rule Supply_Chain_Jscrambler_CSI_Container
{
    meta:
        description = "Detects the custom CSI binary container format used by the compromised jscrambler npm package to bundle platform-specific IronWorm Rust infostealer payloads"
        author = "Actioner"
        date = "2026-07-17"
        reference = "https://socket.dev/blog/jscrambler-supply-chain-attack"
        hash = "a41a523ef9517aab37ed6eea0ec881821bdcb7aefcb5c5f603adc7907f868c86"
        severity = "critical"
        confidence = "high"

    strings:
        $magic = { 1B 43 53 49 01 }
        // Gzip magic (0x1f 0x8b 0x08) — appears in each platform's compressed payload
        $gzip_magic = { 1F 8B 08 }

    condition:
        $magic at 0 and
        filesize > 5MB and filesize < 15MB and
        #gzip_magic >= 2
}

rule Malware_IronWorm_Jscrambler_Rust_Infostealer
{
    meta:
        description = "Detects the IronWorm Rust infostealer binary deployed via the compromised jscrambler npm package. NOTE: ~2,421 strings are ChaCha20-Poly1305 encrypted at rest; this rule keys on strings expected to survive in cleartext (PDB paths, dynamic imports, protocol constants). Effectiveness varies by sample."
        author = "Actioner"
        date = "2026-07-17"
        reference = "https://research.jfrog.com/post/ironworm-returns-rustier-than-ever/"
        hash = "fbbcf4d8f98168f78f5c0c47a9ae56d59ec8ac84a7c9ca6b797fedfb8d62d2bd"
        severity = "high"
        confidence = "medium"

    strings:
        // PE/ELF structural markers
        $pe_magic = "MZ" ascii
        $elf_magic = { 7F 45 4C 46 }

        // PDB path (cleartext in PE debug directory)
        $s1 = "agent.pdb" ascii

        // C2 protocol direction constants (likely cleartext — used in HKDF key derivation)
        $s2 = "csi-a2s" ascii
        $s3 = "csi-s2a" ascii

        // libbpf dynamic import (cleartext in ELF .dynsym / .dynstr)
        $s4 = "bpf_object__open_mem" ascii
        $s5 = "bpf_program__attach" ascii

        // HTTP library / protocol strings (often unencrypted in Rust HTTP crates)
        $s6 = "multipart/form-data" ascii

        // Tor bootstrap detection string
        $s7 = "Bootstrapped 100%" ascii

        // SOCKS5 auth pattern (binary, not string-encrypted)
        $socks5_auth = { 05 01 00 }

    condition:
        filesize < 25MB and
        ($pe_magic at 0 or $elf_magic at 0) and
        4 of ($s*)
}
