// YARA rule for Injective Labs npm supply chain attack — wallet stealer JavaScript payload
// Generated by Actioner | 2026-07-11 | Version 1.0 (DRAFT)

rule Malware_Injective_SDK_WalletStealer
{
    meta:
        description = "Detects the malicious JavaScript payload in @injectivelabs/sdk-ts version 1.20.21 that steals cryptocurrency wallet private keys and mnemonic phrases. Keys on the combination of base64 encoding functions, HTTP POST exfiltration patterns, setTimeout queuing behavior, and wallet key/mnemonic capture logic."
        author = "Actioner"
        date = "2026-07-11"
        reference = "https://www.bleepingcomputer.com/news/security/injective-sdk-on-npm-infected-with-cryptocurrency-wallet-stealer/"
        severity = "critical"

    strings:
        // Base64 encoding of sensitive data (wallet keys/mnemonics)
        $b64_encode1 = "btoa(" ascii
        $b64_encode2 = "Buffer.from(" ascii
        $b64_encode3 = ".toString('base64')" ascii
        $b64_encode4 = ".toString(\"base64\")" ascii

        // HTTP POST exfiltration pattern
        $http_post1 = "POST" ascii
        $http_exfil1 = "headers" ascii
        $http_exfil2 = "fetch(" ascii
        $http_exfil3 = "XMLHttpRequest" ascii
        $http_exfil4 = "axios" ascii

        // Wallet key and mnemonic capture
        $wallet1 = "privateKey" ascii
        $wallet2 = "mnemonic" ascii
        $wallet3 = "seedPhrase" ascii
        $wallet4 = "PrivateKey" ascii
        $wallet5 = "MnemonicWallet" ascii
        $wallet6 = "getPrivateKey" ascii
        $wallet7 = "fromMnemonic" ascii

        // Timer/queue behavior (2-second bundling)
        $timer1 = "setTimeout" ascii
        $timer2 = "2000" ascii
        $timer3 = "setInterval" ascii

        // Injective SDK specific identifiers
        $sdk1 = "@injectivelabs" ascii
        $sdk2 = "injectivelabs" ascii
        $sdk3 = "InjectiveDirectEthSecp256k1Wallet" ascii
        $sdk4 = "InjectiveEthSecp256k1Wallet" ascii

    condition:
        filesize < 5MB and
        (
            // Core pattern: base64 + HTTP exfil + wallet capture + timer queue
            (1 of ($b64_encode*) and 1 of ($http_exfil*) and $http_post1 and 2 of ($wallet*) and 1 of ($timer*) and 1 of ($sdk*)) or
            // Alternative: Injective SDK + wallet + exfiltration in headers
            (2 of ($sdk*) and 2 of ($wallet*) and $http_exfil1 and 1 of ($b64_encode*) and $timer2)
        )
}

rule Malware_Injective_SDK_WalletStealer_PackageJson
{
    meta:
        description = "Detects package.json referencing the known-malicious @injectivelabs/sdk-ts version 1.20.21 in dependencies."
        author = "Actioner"
        date = "2026-07-11"
        reference = "https://www.bleepingcomputer.com/news/security/injective-sdk-on-npm-infected-with-cryptocurrency-wallet-stealer/"
        severity = "high"

    strings:
        $pkg_name = "\"@injectivelabs/sdk-ts\"" ascii
        $mal_ver1 = "\"1.20.21\"" ascii
        $mal_ver2 = ": \"1.20.21\"" ascii
        $dep_block = "dependencies" ascii

    condition:
        filesize < 1MB and
        $pkg_name and
        (1 of ($mal_ver*)) and
        $dep_block
}
