/*
 * MALFEX npm Supply-Chain Campaign - YARA Rules
 * Generated by Actioner on 2026-10-02
 * Reference: https://hackread.com/malfex-npm-windows-rat-steals-discord-browser-data/
 * Reference: https://www.cloudsek.com/blog/malfex-malicious-npm-postinstall-supply-chain-campaign
 */

rule MALFEX_Overlord_RAT_Strings
{
    meta:
        description = "Detects Overlord RAT deployed by the MALFEX npm supply-chain campaign via characteristic Go binary strings and Solana blockchain C2 resolver"
        author = "Actioner"
        date = "2026-10-02"
        reference = "https://hackread.com/malfex-npm-windows-rat-steals-discord-browser-data/"
        severity = "critical"

    strings:
        $go_build = "go.buildid" ascii
        $sol1 = "solana" ascii nocase
        $sol2 = "GetTransaction" ascii
        $sol3 = "rpc" ascii
        $rat1 = "keylogger" ascii nocase
        $rat2 = "screenshot" ascii nocase
        $rat3 = "remoteshell" ascii nocase
        $rat4 = "webcam" ascii nocase
        $ws1 = "websocket" ascii nocase
        $ws2 = "gorilla/websocket" ascii
        $malfex1 = "ScopeSmart" ascii wide
        $malfex2 = "malfexteam2027" ascii
        $malfex3 = "cavecrew" ascii

    condition:
        filesize < 100MB and
        $go_build and
        (1 of ($sol*)) and
        (2 of ($rat*)) and
        (1 of ($ws*)) and
        (1 of ($malfex*))
}

rule MALFEX_AutoIt_Loader_IExpress
{
    meta:
        description = "Detects Microsoft IExpress cabinet containing AutoIt3 loader used by MALFEX campaign to deliver Overlord RAT with EA06 encrypted a3x scripts"
        author = "Actioner"
        date = "2026-10-02"
        reference = "https://www.cloudsek.com/blog/malfex-malicious-npm-postinstall-supply-chain-campaign"
        severity = "high"

    strings:
        $mz = { 4D 5A }
        $autoit = "AutoIt" ascii wide
        $a3x_magic = ".a3x" ascii
        $scope = "ScopeSmart" ascii wide
        $key1 = "malfexteam2027" ascii wide
        $cab = "MSCF" ascii

    condition:
        ($mz at 0 or $cab at 0) and
        filesize < 50MB and
        (
            ($autoit and ($scope or $key1)) or
            ($autoit and $a3x_magic and ($scope or $key1))
        )
}

rule MALFEX_NPM_Postinstall_Script
{
    meta:
        description = "Detects malicious npm postinstall scripts from MALFEX campaign that extract payloads from PNG polyglots using AES-256-CBC decryption"
        author = "Actioner"
        date = "2026-10-02"
        reference = "https://osv.dev/vulnerability/MAL-2026-17216"
        severity = "high"

    strings:
        $key1 = "malfexteam2027" ascii
        $key2 = "nif-runtime-2027" ascii
        $aes = "aes-256-cbc" ascii
        $iend = "IEND" ascii
        $path1 = "node_runtime_helper" ascii
        $path2 = "NodeRuntime" ascii
        $path3 = "gldriver_pre" ascii
        $gh = "cavecrew" ascii

    condition:
        filesize < 5MB and
        (
            ($key1 or $key2) or
            ($aes and $iend and 1 of ($path*)) or
            ($gh and 1 of ($path*))
        )
}

rule MALFEX_movinlike_Stealer_Bundle
{
    meta:
        description = "Detects Node.js credential stealer bundles with characteristics matching the movinlike stealer deployed by the MALFEX campaign. Note: this rule may also match other Node.js stealers with similar Discord/browser/Telegram targeting."
        author = "Actioner"
        date = "2026-10-02"
        reference = "https://www.cloudsek.com/blog/malfex-malicious-npm-postinstall-supply-chain-campaign"
        severity = "high"

    strings:
        $discord1 = "discord" ascii nocase
        $discord2 = "discordapp.com/api/webhooks" ascii
        $token1 = "leveldb" ascii
        $token2 = "Local Storage" ascii
        $browser1 = "Login Data" ascii
        $browser2 = "Cookies" ascii
        $browser3 = "Web Data" ascii
        $tg = "tdata" ascii
        $crypto1 = "wallet" ascii nocase
        $node = "node_modules" ascii
        $malfex1 = "malfexteam2027" ascii
        $malfex2 = "movinlike" ascii
        $c2 = "104.234.65.75" ascii

    condition:
        filesize < 100MB and
        $node and
        (1 of ($discord*)) and
        (1 of ($token*)) and
        (2 of ($browser*)) and
        ($tg or $crypto1) and
        (1 of ($malfex*) or $c2)
}

rule MALFEX_img_to_native_Package
{
    meta:
        description = "Detects known malicious img-to-native npm package files by string combination (package name + key-derivation constant), part of the MALFEX supply-chain campaign"
        author = "Actioner"
        date = "2026-10-02"
        reference = "https://osv.dev/vulnerability/MAL-2026-17216"
        hash1 = "018b3c7012386feefe215ffbc12d9d27228cd4ced623cb568e5ca24746a08d63"
        hash2 = "0958774b99a66f77dcdc9730f565a259d419d9e863315e10160960c538377717"
        hash3 = "7676788d88c2194b8d5c048decfbe06550798ce342af54f8975bc26422d10c53"
        hash4 = "1ddf674c8a1cd844ed91fb0fbba7e61a80210cb11dea1833b57d9cc225a4977c"
        severity = "critical"

    strings:
        $pkg = "img-to-native" ascii
        $key = "nif-runtime-2027" ascii

    condition:
        filesize < 5MB and
        $pkg and $key
}
