/*
 * Operation Navy Ghost - Malicious PyPI Pyrogram Packages Supply Chain Attack
 * Generated by Actioner on 2026-07-01
 * References:
 *   - https://www.bleepingcomputer.com/news/security/malicious-pypi-packages-give-hackers-control-of-telegram-bot-servers/
 *   - https://checkmarx.com/zero-post/operation-navy-ghost-pyrogram-telegram-supplychain-attack/
 */

rule OperationNavyGhost_SecretPy_Backdoor
{
    meta:
        description = "Detects the secret.py backdoor file injected into malicious Pyrogram forks (Operation Navy Ghost)"
        author = "Actioner"
        date = "2026-07-01"
        reference = "https://checkmarx.com/zero-post/operation-navy-ghost-pyrogram-telegram-supplychain-attack/"
        severity = "CRITICAL"
        revision = "v1.1 -- removed standalone import-only branch; imports now require co-occurrence with campaign indicators"

    strings:
        // Hardcoded attacker Telegram IDs
        $owner_id1 = "842320686" ascii
        $owner_id2 = "845521076" ascii
        $owner_id3 = "1675073032" ascii

        // Command handler names
        $cmd_asu = "\"asu\"" ascii
        $cmd_wann = "\"wann\"" ascii
        $cmd_asi = "\"asi\"" ascii
        $cmd_wann2 = "\"wann2\"" ascii

        // Callback trigger strings
        $cb_runtime = "secretruntime" ascii
        $cb_forceclose = "secretforceclose" ascii

        // Backdoor function patterns
        $handler_reg = "add_handler" ascii
        $exec_compile = "exec(compile(" ascii
        $subprocess_run = "subprocess.run" ascii
        $bin_bash = "/bin/bash" ascii
        $reply_doc = "reply_document" ascii

        // Self-exclusion guard
        $self_exclude = ".me.id" ascii

        // Import pattern from helpers
        $import_secret = "from .secret import" ascii
        $import_secret2 = "import pyrogram.helpers.secret" ascii

    condition:
        filesize < 50KB and
        (
            // Match on attacker IDs (any 2 of 3)
            (2 of ($owner_id*)) or
            // Match on specific command handler names (both pairs)
            ($cmd_asu and $cmd_asi) or
            ($cmd_wann and $cmd_wann2) or
            // Match on callback triggers
            ($cb_runtime and $cb_forceclose) or
            // Match on behavioral pattern: handler + exec + shell + exfil
            ($handler_reg and $exec_compile and ($subprocess_run or $bin_bash) and $reply_doc and $self_exclude) or
            // Match on import injection co-occurring with campaign-specific indicators
            (($import_secret or $import_secret2) and any of ($owner_id*, $cmd_*, $cb_*))
        )
}

rule OperationNavyGhost_Package_Metadata
{
    meta:
        description = "Detects malicious Pyrogram fork package metadata strings (Operation Navy Ghost)"
        author = "Actioner"
        date = "2026-07-01"
        reference = "https://checkmarx.com/zero-post/operation-navy-ghost-pyrogram-telegram-supplychain-attack/"
        severity = "HIGH"
        revision = "v1.1 -- replaced generic secret.py with path-qualified string; removed nocase from package names"

    strings:
        $pkg1 = "VLifeGram" ascii
        $pkg2 = "VLife-Gram" ascii
        $pkg3 = "pyrogram-navy" ascii
        $pkg4 = "pyrogram-styled" ascii
        $pkg5 = "pyrogram-zeeb" ascii
        $pkg6 = "kelragram" ascii
        $pkg7 = "sepgram" ascii
        $pkg8 = "pyrogram-kelra" ascii

        // Secret module backdoor indicators (path-qualified)
        $secret_init = "init_secret" ascii
        $secret_path1 = "helpers/secret.py" ascii
        $secret_path2 = "pyrogram/helpers/secret" ascii

    condition:
        filesize < 500KB and
        any of ($pkg*) and
        ($secret_init or $secret_path1 or $secret_path2)
}
