/*
 * Hijacked npm and Go Packages Using VS Code Tasks to Deploy Python Infostealer
 * YARA Detection Rules
 * Generated by Actioner on 2026-06-30
 * References:
 *   - https://thehackernews.com/2026/06/hijacked-npm-and-go-packages-deploy.html
 *   - https://jfrog.com/blog/hijacked-npm-go-packages-vscode-tasks-deploy-infostealer/
 *
 * Attribution: North Korea "Fake Font" / "InvisibleFerret" backdoor campaign
 */

rule Malicious_VSCode_Task_FakeFont_Loader
{
    meta:
        description = "Detects malicious .vscode/tasks.json used by hijacked npm (html-to-gutenberg, fetch-page-assets) and Go packages to auto-execute a JavaScript payload disguised as a font file (fa-solid-400.woff2) when a folder is opened in VS Code"
        author = "Actioner"
        date = "2026-06-30"
        reference = "https://thehackernews.com/2026/06/hijacked-npm-and-go-packages-deploy.html"
        severity = "critical"

    strings:
        // Task label used by the malicious tasks.json
        $task_label  = "eslint-check" ascii wide
        // Auto-run trigger when folder is opened
        $run_trigger = "folderOpen" ascii wide
        // The JS payload disguised as a font file
        $fake_font   = "fa-solid-400.woff2" ascii wide
        // VS Code task configuration key
        $run_on      = "runOn" ascii wide
        // tasks.json in .vscode directory
        $vscode_dir  = ".vscode/tasks.json" ascii wide
        // Shell execution of node against a font file
        $node_exec   = "node" ascii wide

        // Compromised package names
        $pkg1 = "html-to-gutenberg" ascii
        $pkg2 = "fetch-page-assets" ascii

    condition:
        filesize < 5MB and
        (
            // Direct match: tasks.json with eslint-check + folderOpen trigger + font payload
            ($task_label and $run_trigger and $fake_font) or
            // tasks.json referencing the fake font with auto-run
            ($run_on and $run_trigger and $fake_font and $node_exec) or
            // Package archive containing the malicious tasks.json with trigger
            ($vscode_dir and $task_label and $run_trigger) or
            // Known compromised packages with VS Code task artifacts
            (1 of ($pkg*) and $fake_font and $task_label)
        )
}

rule NPM_Go_Package_Blockchain_DeadDrop
{
    meta:
        description = "Detects JavaScript payloads using blockchain dead drop resolvers (TronGrid, Aptos, BSC) to retrieve C2 addresses, as seen in the Fake Font / InvisibleFerret supply chain attack against npm and Go packages"
        author = "Actioner"
        date = "2026-06-30"
        reference = "https://jfrog.com/blog/hijacked-npm-go-packages-vscode-tasks-deploy-infostealer/"
        severity = "critical"

    strings:
        // Blockchain API endpoints used for dead drop resolution
        $api_tron   = "api.trongrid.io" ascii wide
        $api_aptos  = "aptoslabs.com" ascii wide
        $api_bsc    = "bsc-dataseed.binance.org" ascii wide

        // Specific Tron wallet addresses used by the campaign
        $wallet1 = "TMfKQEd7TJJa5xNZJZ2Lep838vrzrs7mAP" ascii wide
        $wallet2 = "TXfxHUet9pJVU1BgVkBAbrES4YUc1nGzcG" ascii wide
        $wallet3 = "TA48dct6rFW8BXsiLAtjFaVFoSuryMjD3v" ascii wide

        // XOR decoding patterns used to decode C2 from blockchain data
        $xor1 = "charCodeAt" ascii
        $xor2 = "fromCharCode" ascii
        $xor3 = "String.fromCharCode" ascii

        // Socket.io backdoor connection fields
        $sock1 = "clientUuid" ascii
        $sock2 = "processId" ascii
        $sock3 = "osType" ascii

        // C2 endpoint paths
        $c2_boot   = "/$/boot" ascii
        $c2_snv    = "/snv" ascii
        $c2_verify = "/verify-human/" ascii

        // Obfuscation: font file name combined with woff2 extension in JS context
        $fake_font_js = "fa-solid-400.woff2" ascii wide

    condition:
        filesize < 15MB and
        (
            // Tron wallet addresses specific to this campaign
            (2 of ($wallet*)) or
            // Blockchain API with XOR decoding (dead drop pattern)
            ($api_tron and 1 of ($xor*)) or
            (1 of ($api_tron, $api_aptos, $api_bsc) and 1 of ($wallet*)) or
            // Socket.io backdoor with blockchain resolver
            (2 of ($sock*) and 1 of ($api_tron, $api_aptos, $api_bsc)) or
            // C2 endpoints combined with blockchain API
            (1 of ($c2_boot, $c2_snv, $c2_verify) and 1 of ($api_tron, $api_aptos, $api_bsc)) or
            // Fake font file reference with blockchain API calls
            ($fake_font_js and 1 of ($api_tron, $api_aptos, $api_bsc)) or
            // Socket.io backdoor with C2 paths
            (2 of ($sock*) and 2 of ($c2_boot, $c2_snv, $c2_verify))
        )
}

rule InvisibleFerret_Python_Infostealer
{
    meta:
        description = "Detects the InvisibleFerret Python infostealer payload attributed to North Korean actors, which steals browser credentials, crypto wallets, and developer tool secrets, exfiltrating data as ZIP archives"
        author = "Actioner"
        date = "2026-06-30"
        reference = "https://thehackernews.com/2026/06/hijacked-npm-and-go-packages-deploy.html"
        severity = "critical"

    strings:
        // Exfiltration archive naming pattern: <hostname>$<username>
        $exfil_pattern = /[a-zA-Z0-9_\-]+\$[a-zA-Z0-9_\-]+\.zip/ ascii

        // Download paths for the Python toolchain
        $dl_pyzip  = "/d/python.zip" ascii wide
        $dl_py7z   = "/d/python.7z" ascii wide
        $dl_7zr    = "7zr.exe" ascii wide
        $dl_getpip = "get-pip.py" ascii wide

        // Socket.io connection identifiers
        $io_uuid    = "clientUuid" ascii
        $io_procid  = "processId" ascii
        $io_ostype  = "osType" ascii

        // C2 endpoint paths
        $c2_ue = "/u/e" ascii
        $c2_uf = "/u/f" ascii

        // Browser credential theft paths (Chromium-based)
        $chrome1 = "Login Data" ascii wide
        $chrome2 = "Local State" ascii wide
        $chrome3 = "Cookies" ascii wide nocase
        $chrome4 = "Web Data" ascii wide

        // Browser credential theft paths (Firefox)
        $firefox1 = "logins.json" ascii wide
        $firefox2 = "key4.db" ascii wide
        $firefox3 = "cert9.db" ascii wide

        // Crypto wallet targets
        $wallet1 = "Exodus" ascii wide nocase
        $wallet2 = "MetaMask" ascii wide nocase
        $wallet3 = "Phantom" ascii wide nocase
        $wallet4 = "Solflare" ascii wide nocase
        $wallet5 = "Atomic" ascii wide nocase

        // Developer tool credential targets
        $dev1 = ".npmrc" ascii
        $dev2 = ".env" ascii
        $dev3 = "credentials" ascii
        $dev4 = ".ssh" ascii

        // Python-specific indicators
        $py_import1 = "import socket" ascii
        $py_import2 = "import zipfile" ascii
        $py_import3 = "import sqlite3" ascii
        $py_import4 = "import json" ascii

    condition:
        filesize < 5MB and
        (
            // Python download artifacts combined with C2 paths
            ($dl_pyzip and $dl_py7z) or
            (1 of ($dl_pyzip, $dl_py7z) and ($dl_7zr or $dl_getpip)) or
            // Socket.io identifiers with browser credential theft
            (2 of ($io_uuid, $io_procid, $io_ostype) and 2 of ($chrome*)) or
            (2 of ($io_uuid, $io_procid, $io_ostype) and 2 of ($firefox*)) or
            // C2 endpoints with browser or wallet theft
            ($c2_ue and $c2_uf and (2 of ($chrome*) or 2 of ($wallet*))) or
            // Browser credential theft combined with wallet theft, Python imports, and campaign anchor
            (2 of ($chrome*) and 2 of ($wallet*) and 2 of ($py_import*) and 1 of ($dev*) and (1 of ($dl_*) or 1 of ($io_*) or 1 of ($c2_*))) or
            // Socket.io backdoor fields with exfil and download patterns
            (2 of ($io_uuid, $io_procid, $io_ostype) and 1 of ($dl_pyzip, $dl_py7z) and 1 of ($c2_ue, $c2_uf)) or
            // Exfil archive naming pattern with C2 or socket.io indicators
            ($exfil_pattern and (1 of ($dl_pyzip, $dl_py7z) or 2 of ($io_uuid, $io_procid, $io_ostype)))
        )
}
