// YARA rule for CVE-2026-46817 — Oracle E-Business Suite Payments File Transmission RCE
// Generated by Actioner | 2026-06-30 | Version 1.0 (DRAFT)

rule CVE_2026_46817_Oracle_EBS_ibytransmit_DeliveryRequest_Payload
{
    meta:
        description = "Detects crafted XML DeliveryRequest payloads targeting the Oracle EBS iPayment File Transmission endpoint (CVE-2026-46817). Keys on the CODEX_PULL transmission scheme and FULL_FILE_PATH parameter observed in honeypot captures, combined with DeliveryRequest XML structure markers."
        author = "Actioner"
        date = "2026-06-30"
        reference = "https://thehackernews.com/2026/06/oracle-e-business-suite-flaw-cve-2026.html"
        cve = "CVE-2026-46817"
        severity = "critical"

    strings:
        $xml_header = "<?xml" ascii nocase
        $delivery_request = "DeliveryRequest" ascii nocase
        $codex_pull = "CODEX_PULL" ascii
        $full_file_path = "FULL_FILE_PATH" ascii
        $ibytransmit = "ibytransmit" ascii nocase

        // Path traversal indicators in FULL_FILE_PATH context
        $traversal_etc_passwd = "/etc/passwd" ascii
        $traversal_etc_shadow = "/etc/shadow" ascii
        $traversal_dotdot = "/../" ascii

    condition:
        filesize < 1MB and (
            ($delivery_request and $codex_pull and $full_file_path) or
            ($delivery_request and $codex_pull and 1 of ($traversal_*)) or
            ($ibytransmit and $delivery_request and $full_file_path) or
            ($xml_header and $codex_pull and $full_file_path)
        )
}

rule CVE_2026_46817_Oracle_EBS_Exploit_UserAgent
{
    meta:
        description = "Detects the ibytransmit-lab-poc User-Agent string associated with privately developed exploit tooling for CVE-2026-46817 (Oracle EBS Payments unauthenticated takeover). Observed in honeypot traffic June 27-28, 2026."
        author = "Actioner"
        date = "2026-06-30"
        reference = "https://www.bleepingcomputer.com/news/security/new-oracle-e-business-suite-flaw-now-exploited-in-attacks/"
        cve = "CVE-2026-46817"
        severity = "critical"

    strings:
        $ua = "ibytransmit-lab-poc" ascii nocase

    condition:
        filesize < 10MB and $ua
}
